'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { BrainCircuit } from 'lucide-react';

type AISummaryProps = {
  summary: string;
};

export function AISummary({ summary }: AISummaryProps) {
  return (
    <Card className="shadow-lg bg-primary/10 border-primary/20">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <BrainCircuit className="h-6 w-6 text-primary" />
          <span>AI-Powered Insights</span>
        </CardTitle>
        <CardDescription>
          This summary is generated by AI to highlight key findings.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <p className="text-foreground/90 leading-relaxed">{summary}</p>
      </CardContent>
    </Card>
  );
}
